Homework 2
================
Jianyou Liu
September 30, 2018

Problem 1
=========

### The code chunk below imports the NYC Subway Station data

``` r
raw_transit_data = read_csv(file = "./hw2_data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
raw_transit_data
```

    ## # A tibble: 1,868 x 32
    ##    Division Line  `Station Name` `Station Latitu~ `Station Longit~ Route1
    ##    <chr>    <chr> <chr>                     <dbl>            <dbl> <chr> 
    ##  1 BMT      4 Av~ 25th St                    40.7            -74.0 R     
    ##  2 BMT      4 Av~ 25th St                    40.7            -74.0 R     
    ##  3 BMT      4 Av~ 36th St                    40.7            -74.0 N     
    ##  4 BMT      4 Av~ 36th St                    40.7            -74.0 N     
    ##  5 BMT      4 Av~ 36th St                    40.7            -74.0 N     
    ##  6 BMT      4 Av~ 45th St                    40.6            -74.0 R     
    ##  7 BMT      4 Av~ 45th St                    40.6            -74.0 R     
    ##  8 BMT      4 Av~ 45th St                    40.6            -74.0 R     
    ##  9 BMT      4 Av~ 45th St                    40.6            -74.0 R     
    ## 10 BMT      4 Av~ 53rd St                    40.6            -74.0 R     
    ## # ... with 1,858 more rows, and 26 more variables: Route2 <chr>,
    ## #   Route3 <chr>, Route4 <chr>, Route5 <chr>, Route6 <chr>, Route7 <chr>,
    ## #   Route8 <int>, Route9 <int>, Route10 <int>, Route11 <int>, `Entrance
    ## #   Type` <chr>, Entry <chr>, `Exit Only` <chr>, Vending <chr>,
    ## #   Staffing <chr>, `Staff Hours` <chr>, ADA <lgl>, `ADA Notes` <chr>,
    ## #   `Free Crossover` <lgl>, `North South Street` <chr>, `East West
    ## #   Street` <chr>, Corner <chr>, `Entrance Latitude` <dbl>, `Entrance
    ## #   Longitude` <dbl>, `Station Location` <chr>, `Entrance Location` <chr>

### The code chunk below cleans the NYC Subway Station data

``` r
tidy1_transit_data = 
  janitor::clean_names(raw_transit_data) %>%
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada ) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))

tidy1_transit_data
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu~ route1 route2
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr> 
    ##  1 4 Av~ 25th St                  40.7            -74.0 R      <NA>  
    ##  2 4 Av~ 25th St                  40.7            -74.0 R      <NA>  
    ##  3 4 Av~ 36th St                  40.7            -74.0 N      R     
    ##  4 4 Av~ 36th St                  40.7            -74.0 N      R     
    ##  5 4 Av~ 36th St                  40.7            -74.0 N      R     
    ##  6 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ##  7 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ##  8 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ##  9 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ## 10 4 Av~ 53rd St                  40.6            -74.0 R      <NA>  
    ## # ... with 1,858 more rows, and 13 more variables: route3 <chr>,
    ## #   route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>,
    ## #   route9 <int>, route10 <int>, route11 <int>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

The dataset contains **line**, **station names**, **station latitude/longitude**, **routes served**, **whether or not there is an entry**, **whether or not there is a vending machine**, **entrance type**, and **Whether ADA compliant** as its variables.

So far, I cleaned the data by first converting the variables names from uppercase to lowercase. Then, I selected those variables of interest. Finally, I converted the *entry* variable from character to logical. The data is still not tidy right now.

The *dimension* of the resulting data set is 1868, 19

### The code chunk below further cleans the dataset

``` r
tidy2_transit_data = distinct(tidy1_transit_data, line, station_name, .keep_all = TRUE)

ada_data = filter(tidy2_transit_data, ada == TRUE)

proportion_data = filter(tidy2_transit_data, vending == "NO")

tidy2_transit_data
```

    ## # A tibble: 465 x 19
    ##    line  station_name station_latitude station_longitu~ route1 route2
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr> 
    ##  1 4 Av~ 25th St                  40.7            -74.0 R      <NA>  
    ##  2 4 Av~ 36th St                  40.7            -74.0 N      R     
    ##  3 4 Av~ 45th St                  40.6            -74.0 R      <NA>  
    ##  4 4 Av~ 53rd St                  40.6            -74.0 R      <NA>  
    ##  5 4 Av~ 59th St                  40.6            -74.0 N      R     
    ##  6 4 Av~ 77th St                  40.6            -74.0 R      <NA>  
    ##  7 4 Av~ 86th St                  40.6            -74.0 R      <NA>  
    ##  8 4 Av~ 95th St                  40.6            -74.0 R      <NA>  
    ##  9 4 Av~ 9th St                   40.7            -74.0 F      G     
    ## 10 4 Av~ Atlantic Av~             40.7            -74.0 B      Q     
    ## # ... with 455 more rows, and 13 more variables: route3 <chr>,
    ## #   route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>,
    ## #   route9 <int>, route10 <int>, route11 <int>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

-   The number of distinct stations is equal to 465.
-   84 stations are ADA compliant.
-   0.5555556 of station entrances/exits without vending allow entrance.(Using the dinstict stations dataset)

### The following code chunk reformats data to allow "route number" and "route name" be distinct variables

``` r
reformat_transit_data = 
  gather(tidy2_transit_data, key = route_number, value = route_name, route1:route11) %>% 
  select(line, station_name, route_number, route_name, everything())

reformat_transit_data
```

    ## # A tibble: 5,115 x 10
    ##    line  station_name route_number route_name station_latitude
    ##    <chr> <chr>        <chr>        <chr>                 <dbl>
    ##  1 4 Av~ 25th St      route1       R                      40.7
    ##  2 4 Av~ 36th St      route1       N                      40.7
    ##  3 4 Av~ 45th St      route1       R                      40.6
    ##  4 4 Av~ 53rd St      route1       R                      40.6
    ##  5 4 Av~ 59th St      route1       N                      40.6
    ##  6 4 Av~ 77th St      route1       R                      40.6
    ##  7 4 Av~ 86th St      route1       R                      40.6
    ##  8 4 Av~ 95th St      route1       R                      40.6
    ##  9 4 Av~ 9th St       route1       F                      40.7
    ## 10 4 Av~ Atlantic Av~ route1       B                      40.7
    ## # ... with 5,105 more rows, and 5 more variables: station_longitude <dbl>,
    ## #   entry <lgl>, vending <chr>, entrance_type <chr>, ada <lgl>

``` r
A_train_data = filter(reformat_transit_data, route_name == "A")
```

The number of distinct stations that serve train A is 60.

Of the stations that serve the A train, 17 are ADA compliant.
